### PR TITLE
Declare bbdb-vcard as a dependency

### PR DESCRIPTION
**Pull request by jian-lin**
bbdb-vcard has been a dependency since
b1c245b81715b0430f7593cee2339e6264104f3d.  However, it is not declared so in semi-pkg.el.
* semi-pkg.el: Declare bbdb-vcard as a dependency.

ref: https://github.com/NixOS/nixpkgs/issues/335442

### CODE REVIEW

**Comment by ikazuhiro** [comment]
It is intended.  bbdb-vcard is an optional package for SEMI-EPG and I think few people actually needs it.  AFAIK, MELPA doesn't support optional package, so I have not set dependency on bbdb-vcard and it works.
Furthermor, [bbdb-vcard package depends on bbdb 3.0](https://melpa.org/#/bbdb-vcard), it isn't really needed by SEMI-EPG.  If SEMI-EPG depended on bbdb-vcard, they were forced to install BBDB regardless their needs.  I couldn't accept such change to make dependecy hell.
Requiring optional package is your package system's issue.  I hope you fix the issue without affecting installation via MELPA.

**Comment by jian-lin** [comment]
Thanks, it makes sense.

**Comment by jian-lin** [comment]
FYI, MELPA [suggests] making separate packages for files needing "optional" dependencies.

> MELPA only looks at the main .el file (or -pkg.el file, if provided, though we discourage that). If you have different optional parts of a large package, each of which has different dependencies, then these should really be published as separate packages.

I guess that does not work here if we want to keep backward compatibility.

[suggests]: https://github.com/melpa/melpa/blob/a74629656e9a23133219a0bd805982f1497b35d7/CONTRIBUTING.org?plain=1#L157-L161

**Comment by ikazuhiro** [comment]
Thank you for the information.  I considered the separation [when I made FLIM-LB depend on oauth2 package](https://github.com/wanderlust/flim/commit/52d86b126bff77aa77d4883f70a05c1bc690953c).  But I've decided not to divide due to some reasons (compatibility with old version or other package system, effort for separation and maintenance).

**Pull request closed without merging**
