### PR TITLE
Fixes so that makeinfo will generate info file

### PR DESCRIPTION
**Pull request by egh**
I was trying to use `makeinfo` to generate an `.info` file, but it was failing on broken cross-references. This should correct the issue. I am unable to read Japanese, so cannot fix the `mime-ui-ja.texi` file.

### CODE REVIEW

**Comment by ikazuhiro** [comment]
I think .texi files of FLIM and SEMI are generated from .sgml files.  But the converter (sinfo.el, according to FLIM's .texi files) may obsolete.  If we will maintain these files, we should first decide which (.texi or .sgml) files to maintain.  If we will maintain only .texi files, .sgml file should be dropped.  Or, if we will maintain .sgml files, we need to revive a converter.

**Comment by egh** [comment]
Thanks for the comment. My preference would be switching to texinfo or some other format to be converted to texinfo rather than use a custom SGML format, but if we don't want to make a decision now I can easily make the change to the SGML file as well.

**Comment by ikazuhiro** [comment]
I'm not familiar with Texinfo, so please tell me if I'm not correct.
1. Why you remove `@setitle` command? stripping `{` and `}` is not enough?
2. As far As I know, Texinfo can have [cross reference to another file](http://www.gnu.org/software/texinfo/manual/texinfo/html_node/Four-and-Five-Arguments.html).  I think you don't need remove all cross reference to another file.

**Comment by egh** [comment]
1. My mistake, it should be there. I will add back.
2. I don't think I removed any valid cross-references. Which were you thinking of? I removed the `mime-en` because this is the same file. I changed `mime-ja` to `mime-ui-ja` because that is the correct name. I removed the `multipart` reference because I could not find a valid `multipart` section in the file.

**Comment by ikazuhiro** [comment]
SEMI's document is `mime-ui-en` and `mime-en` is FLIM's document.  For example, you remove `(@ref{(mime-en)8bit}`, but FLIM's document has `8bit` node.

**Comment by egh** [comment]
Oh, sorry! Thank you, I will correct all these and file a new pull request.

**Pull request closed without merging**
